#use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

install! 'cocoapods', :disable_input_output_paths => true

target 'HoloResource_Example' do
  pod 'HoloResource', :path => '../'
  pod 'HoloResourceForTest', :path => '../HoloResourceForTest/'

  target 'HoloResource_Tests' do
    inherit! :search_paths

    
  end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = "'HOLO_POD_NAME=@(\"#{target}\")'"
    end
  end
end
