#use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

install! 'cocoapods', :disable_input_output_paths => true

target 'HoloResource_Example' do
  pod 'HoloResource', :path => '../'
  pod 'HoloResourceDemoA', :path => '../HoloResourceDemoA/'

  target 'HoloResource_Tests' do
    inherit! :search_paths

    
  end
end


post_install do |installer|
  system "sh /Users/hlgong/holo/HoloResource/HoloResource/Assets/holo_pod_name_config.sh"
#  system "sh /Users/hlgong/holo/HoloResource/HoloResource/Assets/holo_pod_name_config.sh PodA PodB PodC"
end
